### ISSUE TITLE
Driver makes Windows BSOD right after loading.

### ISSUE THREAD

**Issue by waylaa** [VollRagm/KernelBypassSharp#1]
My computer crashes right after loading the driver.sys file using the sc commnad in cmd.

**Comment by VollRagm** [comment]
Please post WinDbg debugging output to further diagnose the bugcheck.

**Comment by xDatx** [comment]
> Please post WinDbg debugging output to further diagnose the bugcheck.

got that in only Win11

**Comment by xDatx** [comment]
[New Text Document.txt](https://github.com/VollRagm/KernelBypassSharp/files/13438672/New.Text.Document.txt)
here is all the context of windbg about bsod, please help sir

**Comment by VollRagm** [comment]
Your debug output indicates that the bugcheck occured in https://github.com/VollRagm/KernelBypassSharp/blob/69a4ef22176b418ec1d808212f0ea10d27e04fb1/KernelBypassSharp/Program.cs#L81.

This likely is due to the signature in Line 77 of Program.cs not being updated. You are going to have to reverse engineer win32kbase.sys to retrieve a new signature for Windows 11.
https://github.com/VollRagm/KernelBypassSharp/blob/69a4ef22176b418ec1d808212f0ea10d27e04fb1/KernelBypassSharp/Program.cs#L77


This only is a PoC, hence I don't keep it updated for newer Windows versions.
